# Generated by Django 2.2.6 on 2019-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_auto_20191112_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
