# Generated by Django 2.2.6 on 2019-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_auto_20191112_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
