# Generated by Django 2.2.6 on 2019-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_auto_20191112_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
        migrations.AddField(
            model_name='myuser',
            name='city_post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
