# Generated by Django 2.2.6 on 2019-11-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0021_likecandidate'),
        ('base_user', '0005_auto_20191114_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CountryModel'),
        ),
    ]
