# Generated by Django 2.2.6 on 2019-11-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0021_likecandidate'),
        ('base_user', '0006_myuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CityModel'),
        ),
    ]
