# Generated by Django 2.2.6 on 2019-11-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0003_auto_20191103_1539'),
        ('CandidateApp', '0003_citymodel_countrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('profile_pict', models.ImageField(upload_to='media')),
                ('company_stage', models.CharField(choices=[('Startapp', 'Startapp'), ('Company', 'Company')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_types', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Remote', 'Remote')], max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('city_post', models.CharField(blank=True, max_length=255, null=True)),
                ('max_salary', models.CharField(max_length=255)),
                ('min_salary', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('starttime', models.CharField(blank=True, max_length=100, null=True)),
                ('endtime', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='post')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CityModel')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CountryModel')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.CategoryModel')),
                ('job_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.SubcategoryModel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
