# Generated by Django 2.2.6 on 2019-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvacancy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companyvacancy',
            name='country',
        ),
    ]
