# Generated by Django 2.2.6 on 2019-11-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0003_citymodel_countrymodel'),
        ('CompanyApp', '0002_auto_20191103_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CityModel'),
        ),
        migrations.AddField(
            model_name='companyvacancy',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CountryModel'),
        ),
    ]
