# Generated by Django 2.2.6 on 2019-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0003_auto_20191103_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
