# Generated by Django 2.2.6 on 2019-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0004_companyvacancy_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvacancy',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
