# Generated by Django 2.2.6 on 2019-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0005_auto_20191105_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvacancy',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
