# Generated by Django 2.2.6 on 2019-11-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0006_auto_20191105_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvacancy',
            name='create_date',
        ),
    ]
