# Generated by Django 2.2.6 on 2019-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0007_remove_companyvacancy_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
