# Generated by Django 2.2.6 on 2019-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0009_applycompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsdfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='CompanyApp.CompanyVacancy')),
            ],
        ),
    ]
