# Generated by Django 2.2.6 on 2019-11-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0010_asdfmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsdfModel',
        ),
    ]
