# Generated by Django 2.2.6 on 2019-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0013_companyvacancy_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
