# Generated by Django 2.2.6 on 2019-11-14 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0020_candidatecv_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyApp', '0019_likemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeMOdel',
            new_name='LikeCompany',
        ),
    ]
