# Generated by Django 2.2.6 on 2019-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0020_auto_20191114_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycompany',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
