# Generated by Django 2.2.6 on 2019-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0021_applycompany_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycompany',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
