# Generated by Django 2.2.6 on 2019-11-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0023_auto_20191115_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycompany',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CandidatePost'),
        ),
    ]
