# Generated by Django 2.2.6 on 2019-11-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0032_auto_20191129_0629'),
        ('CompanyApp', '0024_auto_20191129_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycompany',
            name='post_can',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CandidatePost'),
        ),
        migrations.AlterField(
            model_name='applycompany',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.CompanyVacancy'),
        ),
    ]
