# Generated by Django 2.2.6 on 2019-11-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0025_auto_20191129_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycompany',
            name='post_can',
        ),
    ]
