# Generated by Django 2.2.6 on 2019-11-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0038_auto_20191129_0635'),
        ('CompanyApp', '0029_applycandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidate',
            name='post_can',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateApp.CandidatePost'),
        ),
    ]
