# Generated by Django 2.2.6 on 2019-11-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_citymodel_countrymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityModel',
        ),
        migrations.DeleteModel(
            name='CountryModel',
        ),
    ]
