# Generated by Django 2.2.6 on 2019-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0005_candidatecv_city_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexpedu',
            name='end_date',
            field=models.DateField(),
        ),
    ]
