# Generated by Django 2.2.6 on 2019-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0007_remove_candidateexpedu_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexpedu',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
