# Generated by Django 2.2.6 on 2019-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0008_candidateexpedu_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
