# Generated by Django 2.2.6 on 2019-11-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0009_candidatepost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepost',
            old_name='title',
            new_name='job_title',
        ),
    ]
