# Generated by Django 2.2.6 on 2019-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0014_companyvacancy_slug'),
        ('CandidateApp', '0010_auto_20191112_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepost',
            name='skill',
            field=models.ManyToManyField(to='CompanyApp.SkillsModel'),
        ),
    ]
