# Generated by Django 2.2.6 on 2019-11-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0011_candidatepost_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecv',
            name='work_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
