# Generated by Django 2.2.6 on 2019-11-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20191103_1539'),
        ('CandidateApp', '0014_auto_20191114_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.CategoryModel'),
        ),
    ]
