# Generated by Django 2.2.6 on 2019-11-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0015_candidatecv_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
