# Generated by Django 2.2.6 on 2019-11-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0016_candidatecv_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
