# Generated by Django 2.2.6 on 2019-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0019_auto_20191114_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
