# Generated by Django 2.2.6 on 2019-11-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0021_likecandidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepost',
            old_name='user',
            new_name='name',
        ),
    ]
