# Generated by Django 2.2.6 on 2019-11-28 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0023_auto_20191128_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 17, 41, 2, 854223)),
        ),
    ]
