# Generated by Django 2.2.6 on 2019-11-28 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0024_candidatepost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepost',
            old_name='work_category',
            new_name='job_category',
        ),
        migrations.RenameField(
            model_name='candidatepost',
            old_name='work_subcategory',
            new_name='job_subcategory',
        ),
        migrations.AlterField(
            model_name='candidatepost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 17, 45, 18, 495484)),
        ),
    ]
