# Generated by Django 2.2.6 on 2019-11-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0025_auto_20191128_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepost',
            old_name='job_subcategory',
            new_name='job_sub_category',
        ),
        migrations.AlterField(
            model_name='candidatepost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 17, 46, 3, 938356)),
        ),
    ]
