# Generated by Django 2.2.6 on 2019-11-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0026_auto_20191128_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatepost',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='candidatepost',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 17, 46, 54, 598835)),
        ),
    ]
