# Generated by Django 2.2.6 on 2019-11-28 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0028_auto_20191128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepost',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 18, 15, 11, 774268)),
        ),
    ]
