# Generated by Django 2.2.6 on 2019-11-29 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0029_auto_20191128_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepost',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 6, 27, 52, 849626)),
        ),
    ]
